In [5]:
import numpy as np
a = np.array([1, 2, 3])

In [2]:
print(a)

[1 2 3]


In [8]:
b = np.array([(2, 5, 7), (3, 6, 8), (1, 9, 0)])

In [13]:
print(b)

[[2 5 7]
 [3 6 8]
 [1 9 0]]


In [20]:
c = np.eye(4)

In [21]:
c[0][0] = 0
print(c)

[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [28]:
b.std()

3.02254900194121