In [2]:
import pandas as pd
alunos = {'Nome':['Caio', 'Ricardo', 'Pedro', 'Roberto', 'Carlos'],
         'Nota':[4, 5.5, 7.9, 10, 9.5],
         'Aprovado':[False, False, True, True, True]}

In [3]:
dataFrame = pd.DataFrame(alunos)

In [8]:
dataFrame

Nome  Nota  Aprovado
0     Caio   4.0     False
1  Ricardo   5.5     False
2    Pedro   7.9      True
3  Roberto  10.0      True
4   Carlos   9.5      True

In [14]:
objeto = pd.Series([2, 6, 9, 10, 5])
print(objeto)

0     2
1     6
2     9
3    10
4     5
dtype: int64


In [18]:
import numpy as np
arrayUni =  np.array([2, 6, 9, 10, 5])
arrayBi = np.array([(2, 6, 9, 10, 5), (6, 12, 15, 0, 9)])
print(arrayUni)
print(arrayBi)

[ 2  6  9 10  5]
[[ 2  6  9 10  5]
 [ 6 12 15  0  9]]


In [22]:
objeto2 = pd.Series(arrayUni)
print(objeto2)

0     2
1     6
2     9
3    10
4     5
dtype: int32
